// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASfMUMrMIN3JEuW73R9jY1E4Of0PbO86k',
    appId: '1:237877067953:web:95125550d874ad90cee290',
    messagingSenderId: '237877067953',
    projectId: 'library-management-system-fl',
    authDomain: 'library-management-system-fl.firebaseapp.com',
    storageBucket: 'library-management-system-fl.firebasestorage.app',
    measurementId: 'G-Z4KTM31F1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf15NNo2GYvgRaJRow3munQaJwFFj9qKs',
    appId: '1:237877067953:android:6906cafcb104d435cee290',
    messagingSenderId: '237877067953',
    projectId: 'library-management-system-fl',
    storageBucket: 'library-management-system-fl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKosj8rFS_ndsb--NyeTbJPzz4YzF9-o4',
    appId: '1:237877067953:ios:6ebb65600b087988cee290',
    messagingSenderId: '237877067953',
    projectId: 'library-management-system-fl',
    storageBucket: 'library-management-system-fl.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKosj8rFS_ndsb--NyeTbJPzz4YzF9-o4',
    appId: '1:237877067953:ios:6ebb65600b087988cee290',
    messagingSenderId: '237877067953',
    projectId: 'library-management-system-fl',
    storageBucket: 'library-management-system-fl.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASfMUMrMIN3JEuW73R9jY1E4Of0PbO86k',
    appId: '1:237877067953:web:52f49b57e9f0a48ccee290',
    messagingSenderId: '237877067953',
    projectId: 'library-management-system-fl',
    authDomain: 'library-management-system-fl.firebaseapp.com',
    storageBucket: 'library-management-system-fl.firebasestorage.app',
    measurementId: 'G-CCNP0C497J',
  );
}
